#!/usr/bin/env bash
set -Eeuo pipefail

action="${1:-}"
shift || true

deployment_root=/opt/hirescope
state_dir="$deployment_root/.deploy"
current_state="$state_dir/current-success.env"
previous_state="$state_dir/previous-success.env"
env_file="$deployment_root/.env.production"

require_sha() {
  [[ "$1" =~ ^[0-9a-f]{40}$ ]] || { echo "Invalid full commit SHA." >&2; return 1; }
}

require_digest() {
  [[ "$1" =~ ^sha256:[0-9a-f]{64}$ ]] || { echo "Invalid image digest." >&2; return 1; }
}

load_state() {
  local state_file="$1"
  test -s "$state_file"
  unset STATE_KIND DEPLOY_SHA API_IMAGE API_DIGEST WORKER_IMAGE WORKER_DIGEST
  unset WEB_IMAGE WEB_DIGEST MIGRATE_IMAGE MIGRATE_DIGEST COMPOSE_FILE
  # The file is generated by record_success after all values pass strict validation.
  # shellcheck disable=SC1090
  source "$state_file"
  : "${STATE_KIND:?Missing STATE_KIND}"
  require_sha "$DEPLOY_SHA"
  for service in API WORKER WEB MIGRATE; do
    local image_variable="${service}_IMAGE"
    local digest_variable="${service}_DIGEST"
    require_digest "${!digest_variable}"
    if [[ "$STATE_KIND" == immutable ]]; then
      [[ "${!image_variable}" == ghcr.io/*:"$DEPLOY_SHA" ]]
    elif [[ "$STATE_KIND" == local-image ]]; then
      [[ "${!image_variable}" == "${!digest_variable}" ]]
    else
      echo "Unknown deployment state kind: $STATE_KIND" >&2
      return 1
    fi
  done
  test -s "$COMPOSE_FILE"
}

login_ghcr() {
  local registry_user="$1"
  local registry_token
  IFS= read -r registry_token
  test -n "$registry_token"
  printf '%s' "$registry_token" | docker login ghcr.io --username "$registry_user" --password-stdin >/dev/null
  unset registry_token
}

set_image_environment() {
  export HIRESCOPE_API_IMAGE="$API_IMAGE"
  export HIRESCOPE_WORKER_IMAGE="$WORKER_IMAGE"
  export HIRESCOPE_WEB_IMAGE="$WEB_IMAGE"
  export HIRESCOPE_MIGRATE_IMAGE="$MIGRATE_IMAGE"
}

image_has_digest() {
  local image="$1"
  local digest="$2"
  local repository="${image%:*}"
  docker image inspect "$image" --format '{{range .RepoDigests}}{{println .}}{{end}}' \
    | grep -Fqx "${repository}@${digest}"
}

wait_for_app_services() {
  local -n compose_command=$1
  local deadline=$((SECONDS + 300))
  local pending=(api worker web)

  while (( ${#pending[@]} > 0 && SECONDS < deadline )); do
    local remaining=()
    local service container_id status health
    for service in "${pending[@]}"; do
      container_id="$("${compose_command[@]}" ps -q "$service")"
      if [[ -z "$container_id" ]]; then
        remaining+=("$service")
        continue
      fi
      status="$(docker inspect --format '{{.State.Status}}' "$container_id")"
      health="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$container_id")"
      if [[ "$status" == running && "$health" == healthy ]]; then
        continue
      fi
      if [[ "$status" == exited || "$status" == dead || "$health" == unhealthy ]]; then
        echo "$service failed readiness: status=$status health=$health" >&2
        return 1
      fi
      remaining+=("$service")
    done
    pending=("${remaining[@]}")
    (( ${#pending[@]} == 0 )) || sleep 5
  done

  (( ${#pending[@]} == 0 )) || { echo "Timed out waiting for: ${pending[*]}" >&2; return 1; }
}

verify_running_service() {
  local -n compose_command=$1
  local service="$2"
  local image="$3"
  local expected_sha="$4"
  local require_identity="${5:-true}"
  local container_id expected_image_id actual_image_id revision runtime_sha

  container_id="$("${compose_command[@]}" ps -q "$service")"
  test -n "$container_id"
  expected_image_id="$(docker image inspect "$image" --format '{{.Id}}')"
  actual_image_id="$(docker inspect "$container_id" --format '{{.Image}}')"
  [[ "$actual_image_id" == "$expected_image_id" ]]
  [[ "$require_identity" == true ]] || return 0
  revision="$(docker inspect "$container_id" --format '{{index .Config.Labels "org.opencontainers.image.revision"}}')"
  [[ "$revision" == "$expected_sha" ]]
  runtime_sha="$(docker inspect "$container_id" --format '{{range .Config.Env}}{{println .}}{{end}}' | sed -n 's/^APP_COMMIT_SHA=//p')"
  [[ "$runtime_sha" == "$expected_sha" ]]
}

snapshot_legacy_rollback_state() {
  local fallback_compose_file="$1"
  local API_IMAGE API_DIGEST WORKER_IMAGE WORKER_DIGEST WEB_IMAGE WEB_DIGEST
  local MIGRATE_IMAGE MIGRATE_DIGEST
  test -s "$deployment_root/docker-compose.prod.yml"
  local legacy_sha
  legacy_sha="$(git -C "$deployment_root" rev-parse HEAD)"
  require_sha "$legacy_sha"

  local legacy_compose=(docker compose --env-file "$env_file" -f "$deployment_root/docker-compose.prod.yml")
  local service container_id image_id
  for service in api worker web; do
    container_id="$("${legacy_compose[@]}" ps -q "$service")"
    test -n "$container_id"
    image_id="$(docker inspect "$container_id" --format '{{.Image}}')"
    require_digest "$image_id"
    printf -v "${service^^}_IMAGE" '%s' "$image_id"
    printf -v "${service^^}_DIGEST" '%s' "$image_id"
  done
  image_id="$("${legacy_compose[@]}" --profile migration images -q migrate)"
  require_digest "$image_id"
  MIGRATE_IMAGE="$image_id"
  MIGRATE_DIGEST="$image_id"

  umask 077
  {
    printf 'STATE_KIND=local-image\n'
    printf 'DEPLOY_SHA=%q\n' "$legacy_sha"
    printf 'API_IMAGE=%q\nAPI_DIGEST=%q\n' "$API_IMAGE" "$API_DIGEST"
    printf 'WORKER_IMAGE=%q\nWORKER_DIGEST=%q\n' "$WORKER_IMAGE" "$WORKER_DIGEST"
    printf 'WEB_IMAGE=%q\nWEB_DIGEST=%q\n' "$WEB_IMAGE" "$WEB_DIGEST"
    printf 'MIGRATE_IMAGE=%q\nMIGRATE_DIGEST=%q\n' "$MIGRATE_IMAGE" "$MIGRATE_DIGEST"
    printf 'COMPOSE_FILE=%q\n' "$fallback_compose_file"
  } > "${current_state}.tmp"
  mv "${current_state}.tmp" "$current_state"
  echo "Captured pre-immutable application rollback baseline at $legacy_sha."
}

rollback_apps() {
  if ! load_state "$current_state"; then
    echo "No previous successful immutable deployment is available for automatic app rollback." >&2
    return 1
  fi

  set_image_environment
  local compose=(docker compose --env-file "$env_file" -f "$COMPOSE_FILE")
  if [[ "$STATE_KIND" == immutable ]]; then
    "${compose[@]}" pull api worker web
  fi
  "${compose[@]}" up -d --force-recreate api worker web
  wait_for_app_services compose
  local require_identity=true
  [[ "$STATE_KIND" == immutable ]] || require_identity=false
  verify_running_service compose api "$API_IMAGE" "$DEPLOY_SHA" "$require_identity"
  verify_running_service compose worker "$WORKER_IMAGE" "$DEPLOY_SHA" "$require_identity"
  verify_running_service compose web "$WEB_IMAGE" "$DEPLOY_SHA" "$require_identity"
  echo "Application services rolled back to $DEPLOY_SHA; database migrations were not rolled back."
}

deploy() {
  local target_sha="$1"
  local registry_user="$2"
  local public_origin_base64="$3"
  API_IMAGE="$4"
  API_DIGEST="$5"
  WORKER_IMAGE="$6"
  WORKER_DIGEST="$7"
  WEB_IMAGE="$8"
  WEB_DIGEST="$9"
  MIGRATE_IMAGE="${10}"
  MIGRATE_DIGEST="${11}"
  COMPOSE_FILE="$state_dir/compose-${target_sha}.yml"

  require_sha "$target_sha"
  for digest in "$API_DIGEST" "$WORKER_DIGEST" "$WEB_DIGEST" "$MIGRATE_DIGEST"; do require_digest "$digest"; done
  for image in "$API_IMAGE" "$WORKER_IMAGE" "$WEB_IMAGE" "$MIGRATE_IMAGE"; do
    [[ "$image" == ghcr.io/*:"$target_sha" ]]
  done
  test -s "$COMPOSE_FILE"
  test -s "$env_file"

  local public_origin
  public_origin="$(printf '%s' "$public_origin_base64" | base64 --decode)"
  [[ "$public_origin" =~ ^https?://[^/]+$ ]]
  export CORS_ALLOWED_ORIGINS="$public_origin"
  set_image_environment

  local compose=(docker compose --env-file "$env_file" -f "$COMPOSE_FILE")
  "${compose[@]}" config --quiet
  login_ghcr "$registry_user"
  "${compose[@]}" --profile migration pull migrate api worker web

  image_has_digest "$API_IMAGE" "$API_DIGEST"
  image_has_digest "$WORKER_IMAGE" "$WORKER_DIGEST"
  image_has_digest "$WEB_IMAGE" "$WEB_DIGEST"
  image_has_digest "$MIGRATE_IMAGE" "$MIGRATE_DIGEST"

  for service_image in "$API_IMAGE" "$WORKER_IMAGE" "$WEB_IMAGE"; do
    [[ "$(docker image inspect "$service_image" --format '{{index .Config.Labels "org.opencontainers.image.revision"}}')" == "$target_sha" ]]
  done

  if ! test -s "$current_state"; then
    snapshot_legacy_rollback_state "$COMPOSE_FILE"
    set_image_environment
  fi

  "${compose[@]}" --profile migration run --rm migrate

  local new_containers_started=false
  on_deploy_failure() {
    local exit_status=$?
    trap - ERR
    if [[ "$new_containers_started" == true ]]; then
      echo "New application containers failed; attempting app-only rollback." >&2
      rollback_apps || true
    fi
    exit "$exit_status"
  }
  trap on_deploy_failure ERR

  "${compose[@]}" up -d --force-recreate api worker web
  new_containers_started=true
  wait_for_app_services compose
  verify_running_service compose api "$API_IMAGE" "$target_sha"
  verify_running_service compose worker "$WORKER_IMAGE" "$target_sha"
  verify_running_service compose web "$WEB_IMAGE" "$target_sha"

  local nonce
  nonce="${target_sha}-$(date +%s%N)"
  local headers_file body_file
  headers_file="$(mktemp)"
  body_file="$(mktemp)"
  trap 'rm -f "$headers_file" "$body_file"; trap - RETURN' RETURN

  curl -fsS -H 'Cache-Control: no-cache' -D "$headers_file" -o "$body_file" \
    "http://127.0.0.1:3000/api/v1/version?deploy_sha=${target_sha}&nonce=${nonce}"
  grep -Eiq '^cache-control:.*no-store' "$headers_file"
  grep -Fq "\"commitSha\":\"${target_sha}\"" "$body_file"

  curl -fsS -H 'Cache-Control: no-cache' -D "$headers_file" -o "$body_file" \
    "http://127.0.0.1:3000/_version?deploy_sha=${target_sha}&nonce=${nonce}"
  grep -Eiq '^cache-control:.*no-store' "$headers_file"
  grep -Eiq "^x-app-commit-sha: *${target_sha}" "$headers_file"
  grep -Eiq "^x-next-build-id: *${target_sha}" "$headers_file"
  grep -Fq "\"commitSha\":\"${target_sha}\"" "$body_file"
  grep -Fq "\"nextBuildId\":\"${target_sha}\"" "$body_file"

  local logout_status
  logout_status="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 10 \
    -X POST -H "Origin: $public_origin" \
    http://127.0.0.1:3000/api/v1/auth/logout)"
  [[ "$logout_status" == 204 ]] || {
    echo "Production auth origin smoke failed with HTTP $logout_status." >&2
    return 1
  }

  local worker_id
  worker_id="$("${compose[@]}" ps -q worker)"
  local worker_logs
  worker_logs="$(docker logs "$worker_id" 2>&1)"
  grep -Fq "Worker starting commit_sha=${target_sha}" <<< "$worker_logs"

  trap - ERR
  echo "Internal image, OCI revision, runtime SHA, API, Web, and Worker checks passed for $target_sha."
}

record_success() {
  local target_sha="$1"
  API_IMAGE="$2"
  API_DIGEST="$3"
  WORKER_IMAGE="$4"
  WORKER_DIGEST="$5"
  WEB_IMAGE="$6"
  WEB_DIGEST="$7"
  MIGRATE_IMAGE="$8"
  MIGRATE_DIGEST="$9"
  COMPOSE_FILE="$state_dir/compose-${target_sha}.yml"

  require_sha "$target_sha"
  for digest in "$API_DIGEST" "$WORKER_DIGEST" "$WEB_DIGEST" "$MIGRATE_DIGEST"; do require_digest "$digest"; done
  test -s "$COMPOSE_FILE"
  if test -s "$current_state"; then cp "$current_state" "$previous_state"; fi
  umask 077
  {
    printf 'STATE_KIND=immutable\n'
    printf 'DEPLOY_SHA=%q\n' "$target_sha"
    printf 'API_IMAGE=%q\nAPI_DIGEST=%q\n' "$API_IMAGE" "$API_DIGEST"
    printf 'WORKER_IMAGE=%q\nWORKER_DIGEST=%q\n' "$WORKER_IMAGE" "$WORKER_DIGEST"
    printf 'WEB_IMAGE=%q\nWEB_DIGEST=%q\n' "$WEB_IMAGE" "$WEB_DIGEST"
    printf 'MIGRATE_IMAGE=%q\nMIGRATE_DIGEST=%q\n' "$MIGRATE_IMAGE" "$MIGRATE_DIGEST"
    printf 'COMPOSE_FILE=%q\n' "$COMPOSE_FILE"
  } > "${current_state}.tmp"
  mv "${current_state}.tmp" "$current_state"
  echo "Recorded successful production deployment $target_sha."
}

case "$action" in
  deploy)
    (( $# == 11 )) || { echo "Invalid deploy arguments." >&2; exit 2; }
    deploy "$@"
    ;;
  rollback)
    (( $# == 1 )) || { echo "Invalid rollback arguments." >&2; exit 2; }
    login_ghcr "$1"
    rollback_apps
    ;;
  record-success)
    (( $# == 9 )) || { echo "Invalid record arguments." >&2; exit 2; }
    record_success "$@"
    ;;
  *)
    echo "Unknown action: $action" >&2
    exit 2
    ;;
esac
