#!/usr/bin/env bash
set -Eeuo pipefail

action="${1:-}"
shift || true

deployment_root=/opt/hirescope
state_dir="$deployment_root/.deploy"
current_state="$state_dir/current-success.env"
previous_state="$state_dir/previous-success.env"
env_file="$deployment_root/.env.production"
deploy_env_file="$deployment_root/.env.deploy"
compose_source_file="$deployment_root/docker-compose.prod.yml"
deployment_lock="$state_dir/deploy.lock"
pull_timeout_seconds=600
pull_max_attempts=3
migration_timeout_seconds=600
health_command_timeout_seconds=15
health_deadline_seconds=300

require_sha() {
  [[ "$1" =~ ^[0-9a-f]{40}$ ]] || { echo "Invalid full commit SHA." >&2; return 1; }
}

require_digest() {
  [[ "$1" =~ ^sha256:[0-9a-f]{64}$ ]] || { echo "Invalid image digest." >&2; return 1; }
}

load_state() {
  local state_file="$1"
  test -s "$state_file"
  unset STATE_KIND DEPLOY_SHA API_IMAGE API_DIGEST WORKER_IMAGE WORKER_DIGEST
  unset WEB_IMAGE WEB_DIGEST MIGRATE_IMAGE MIGRATE_DIGEST COMPOSE_FILE
  # The file is generated by record_success after all values pass strict validation.
  # shellcheck disable=SC1090
  source "$state_file"
  : "${STATE_KIND:?Missing STATE_KIND}"
  require_sha "$DEPLOY_SHA"
  for service in API WORKER WEB MIGRATE; do
    local image_variable="${service}_IMAGE"
    local digest_variable="${service}_DIGEST"
    require_digest "${!digest_variable}"
    if [[ "$STATE_KIND" == immutable ]]; then
      [[ "${!image_variable}" =~ ^[a-z0-9.-]+(:[0-9]+)?/[a-z0-9._/-]+:"$DEPLOY_SHA"$ ]]
    elif [[ "$STATE_KIND" == local-image ]]; then
      [[ "${!image_variable}" == "${!digest_variable}" ]]
    else
      echo "Unknown deployment state kind: $STATE_KIND" >&2
      return 1
    fi
  done
  test -s "$COMPOSE_FILE"
}

read_deploy_value() {
  local key="$1"
  local value
  value="$(sed -n "s/^${key}=//p" "$deploy_env_file")"
  [[ "$value" != *$'\n'* ]]
  printf '%s' "$value"
}

load_deploy_config() {
  test -s "$deploy_env_file"
  ACR_PUBLIC_REGISTRY="$(read_deploy_value ACR_PUBLIC_REGISTRY)"
  ACR_NAMESPACE="$(read_deploy_value ACR_NAMESPACE)"
  [[ "$ACR_PUBLIC_REGISTRY" =~ ^[a-z0-9.-]+(:[0-9]+)?$ ]] || {
    echo "ACR_PUBLIC_REGISTRY must be the exact public Registry domain without a scheme or path." >&2
    return 1
  }
  [[ "$ACR_NAMESPACE" =~ ^[a-z0-9]+([._-][a-z0-9]+)*$ ]] || {
    echo "ACR_NAMESPACE is invalid." >&2
    return 1
  }
}

set_image_environment() {
  export HIRESCOPE_API_IMAGE="$API_IMAGE"
  export HIRESCOPE_WORKER_IMAGE="$WORKER_IMAGE"
  export HIRESCOPE_WEB_IMAGE="$WEB_IMAGE"
  export HIRESCOPE_MIGRATE_IMAGE="$MIGRATE_IMAGE"
}

image_has_digest() {
  local image="$1"
  local digest="$2"
  local repository="${image%:*}"
  docker image inspect "$image" --format '{{range .RepoDigests}}{{println .}}{{end}}' \
    | grep -Fqx "${repository}@${digest}"
}

get_image_digest() {
  local image="$1"
  local repository="${image%:*}"
  local digest_reference
  digest_reference="$(docker image inspect "$image" --format '{{range .RepoDigests}}{{println .}}{{end}}' \
    | grep -F "${repository}@" | head -n 1)"
  local digest="${digest_reference#*@}"
  require_digest "$digest"
  printf '%s' "$digest"
}

pull_service_image() {
  local -n compose_command=$1
  local service="$2"
  local attempt exit_status

  echo "Image pull started: $service."
  for (( attempt = 1; attempt <= pull_max_attempts; attempt++ )); do
    echo "Image pull attempt ${attempt}/${pull_max_attempts}: $service."
    if timeout --signal=TERM --kill-after=30s "${pull_timeout_seconds}s" \
      env COMPOSE_PARALLEL_LIMIT=1 \
      "${compose_command[@]}" --profile migration pull "$service"; then
      echo "Image pull completed: $service on attempt $attempt."
      return 0
    else
      exit_status=$?
    fi

    if (( attempt < pull_max_attempts )); then
      if (( exit_status == 124 )); then
        echo "Image pull attempt ${attempt}/${pull_max_attempts} timed out for $service; retrying." >&2
      else
        echo "Image pull attempt ${attempt}/${pull_max_attempts} exited with status $exit_status for $service; retrying." >&2
      fi
      sleep 5
    fi
  done

  if (( exit_status == 124 )); then
    echo "Image pull failed: $service timed out after ${pull_max_attempts} attempts of ${pull_timeout_seconds}s." >&2
  else
    echo "Image pull failed: $service exited with status $exit_status." >&2
  fi
  return "$exit_status"
}

run_migration() {
  local -n compose_command=$1
  local exit_status

  echo "Migration started."
  if timeout --signal=TERM --kill-after=30s "${migration_timeout_seconds}s" \
    "${compose_command[@]}" --profile migration run --rm migrate; then
    echo "Migration completed."
    return 0
  else
    exit_status=$?
  fi

  if (( exit_status == 124 )); then
    echo "Migration failed: timed out after ${migration_timeout_seconds}s." >&2
  else
    echo "Migration failed: exited with status $exit_status." >&2
  fi
  return "$exit_status"
}

run_health_command() {
  local description="$1"
  shift
  local exit_status

  if timeout --signal=TERM --kill-after=5s "${health_command_timeout_seconds}s" "$@"; then
    return 0
  else
    exit_status=$?
  fi

  if (( exit_status == 124 )); then
    echo "Health check command failed: $description timed out after ${health_command_timeout_seconds}s." >&2
  else
    echo "Health check command failed: $description exited with status $exit_status." >&2
  fi
  return "$exit_status"
}

wait_for_app_services() {
  local -n compose_command=$1
  local deadline=$((SECONDS + health_deadline_seconds))
  local pending=(api worker web)

  while (( ${#pending[@]} > 0 && SECONDS < deadline )); do
    local remaining=()
    local service container_id status health
    for service in "${pending[@]}"; do
      container_id="$(run_health_command "$service container lookup" \
        "${compose_command[@]}" ps -q "$service")"
      if [[ -z "$container_id" ]]; then
        remaining+=("$service")
        continue
      fi
      status="$(run_health_command "$service container status" \
        docker inspect --format '{{.State.Status}}' "$container_id")"
      health="$(run_health_command "$service container health" \
        docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$container_id")"
      if [[ "$status" == running && "$health" == healthy ]]; then
        continue
      fi
      if [[ "$status" == exited || "$status" == dead || "$health" == unhealthy ]]; then
        echo "$service failed readiness: status=$status health=$health" >&2
        return 1
      fi
      remaining+=("$service")
    done
    pending=("${remaining[@]}")
    (( ${#pending[@]} == 0 )) || sleep 5
  done

  (( ${#pending[@]} == 0 )) || { echo "Timed out waiting for: ${pending[*]}" >&2; return 1; }
}

verify_running_service() {
  local -n compose_command=$1
  local service="$2"
  local image="$3"
  local expected_sha="$4"
  local require_identity="${5:-true}"
  local container_id expected_image_id actual_image_id revision runtime_sha

  container_id="$(run_health_command "$service identity container lookup" \
    "${compose_command[@]}" ps -q "$service")"
  test -n "$container_id"
  expected_image_id="$(run_health_command "$service expected image lookup" \
    docker image inspect "$image" --format '{{.Id}}')"
  actual_image_id="$(run_health_command "$service runtime image lookup" \
    docker inspect "$container_id" --format '{{.Image}}')"
  [[ "$actual_image_id" == "$expected_image_id" ]]
  [[ "$require_identity" == true ]] || return 0
  revision="$(run_health_command "$service OCI revision lookup" \
    docker inspect "$container_id" --format '{{index .Config.Labels "org.opencontainers.image.revision"}}')"
  [[ "$revision" == "$expected_sha" ]]
  runtime_sha="$(run_health_command "$service runtime SHA lookup" \
    docker inspect "$container_id" --format '{{range .Config.Env}}{{println .}}{{end}}' \
    | sed -n 's/^APP_COMMIT_SHA=//p')"
  [[ "$runtime_sha" == "$expected_sha" ]]
}

snapshot_legacy_rollback_state() {
  local fallback_compose_file="$1"
  local API_IMAGE API_DIGEST WORKER_IMAGE WORKER_DIGEST WEB_IMAGE WEB_DIGEST
  local MIGRATE_IMAGE MIGRATE_DIGEST
  test -s "$fallback_compose_file"
  local legacy_sha
  local api_container_id
  api_container_id="$(docker ps -q \
    --filter label=com.docker.compose.project=hirescope-ai \
    --filter label=com.docker.compose.service=api | head -n 1)"
  test -n "$api_container_id"
  legacy_sha="$(docker inspect "$api_container_id" --format '{{range .Config.Env}}{{println .}}{{end}}' \
    | sed -n 's/^APP_COMMIT_SHA=//p')"
  if [[ ! "$legacy_sha" =~ ^[0-9a-f]{40}$ ]] && git -C "$deployment_root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    legacy_sha="$(git -C "$deployment_root" rev-parse HEAD)"
  fi
  require_sha "$legacy_sha"

  local service container_id image_id
  for service in api worker web; do
    container_id="$(docker ps -q \
      --filter label=com.docker.compose.project=hirescope-ai \
      --filter "label=com.docker.compose.service=${service}" | head -n 1)"
    test -n "$container_id"
    image_id="$(docker inspect "$container_id" --format '{{.Image}}')"
    require_digest "$image_id"
    printf -v "${service^^}_IMAGE" '%s' "$image_id"
    printf -v "${service^^}_DIGEST" '%s' "$image_id"
  done
  MIGRATE_IMAGE="$API_IMAGE"
  MIGRATE_DIGEST="$API_DIGEST"

  umask 077
  {
    printf 'STATE_KIND=local-image\n'
    printf 'DEPLOY_SHA=%q\n' "$legacy_sha"
    printf 'API_IMAGE=%q\nAPI_DIGEST=%q\n' "$API_IMAGE" "$API_DIGEST"
    printf 'WORKER_IMAGE=%q\nWORKER_DIGEST=%q\n' "$WORKER_IMAGE" "$WORKER_DIGEST"
    printf 'WEB_IMAGE=%q\nWEB_DIGEST=%q\n' "$WEB_IMAGE" "$WEB_DIGEST"
    printf 'MIGRATE_IMAGE=%q\nMIGRATE_DIGEST=%q\n' "$MIGRATE_IMAGE" "$MIGRATE_DIGEST"
    printf 'COMPOSE_FILE=%q\n' "$fallback_compose_file"
  } > "${current_state}.tmp"
  mv "${current_state}.tmp" "$current_state"
  echo "Captured pre-immutable application rollback baseline at $legacy_sha."
}

rollback_apps() {
  if ! load_state "$current_state"; then
    echo "No previous successful immutable deployment is available for automatic app rollback." >&2
    return 1
  fi

  set_image_environment
  local compose=(docker compose --env-file "$env_file" -f "$COMPOSE_FILE")
  if [[ "$STATE_KIND" == immutable ]]; then
    for service in api worker web; do
      local image_variable="${service^^}_IMAGE"
      local digest_variable="${service^^}_DIGEST"
      if ! image_has_digest "${!image_variable}" "${!digest_variable}"; then
        pull_service_image compose "$service"
      fi
    done
  fi
  "${compose[@]}" up --no-deps -d --force-recreate api worker web
  wait_for_app_services compose
  local require_identity=true
  [[ "$STATE_KIND" == immutable ]] || require_identity=false
  verify_running_service compose api "$API_IMAGE" "$DEPLOY_SHA" "$require_identity"
  verify_running_service compose worker "$WORKER_IMAGE" "$DEPLOY_SHA" "$require_identity"
  verify_running_service compose web "$WEB_IMAGE" "$DEPLOY_SHA" "$require_identity"
  echo "Application services rolled back to $DEPLOY_SHA; database migrations were not rolled back."
}

deploy() {
  local target_sha="$1"
  COMPOSE_FILE="$state_dir/compose-${target_sha}.yml"

  require_sha "$target_sha"
  load_deploy_config
  test -s "$env_file"
  test -s "$compose_source_file"

  API_IMAGE="$ACR_PUBLIC_REGISTRY/$ACR_NAMESPACE/api:$target_sha"
  WORKER_IMAGE="$ACR_PUBLIC_REGISTRY/$ACR_NAMESPACE/worker:$target_sha"
  WEB_IMAGE="$ACR_PUBLIC_REGISTRY/$ACR_NAMESPACE/web:$target_sha"
  MIGRATE_IMAGE="$ACR_PUBLIC_REGISTRY/$ACR_NAMESPACE/migrate:$target_sha"

  install -m 600 "$compose_source_file" "$COMPOSE_FILE"
  set_image_environment

  local compose=(docker compose --env-file "$env_file" -f "$COMPOSE_FILE")
  "${compose[@]}" config --quiet
  local service
  for service in migrate api worker web; do
    pull_service_image compose "$service"
  done

  API_DIGEST="$(get_image_digest "$API_IMAGE")"
  WORKER_DIGEST="$(get_image_digest "$WORKER_IMAGE")"
  WEB_DIGEST="$(get_image_digest "$WEB_IMAGE")"
  MIGRATE_DIGEST="$(get_image_digest "$MIGRATE_IMAGE")"

  for service_image in "$API_IMAGE" "$WORKER_IMAGE" "$WEB_IMAGE" "$MIGRATE_IMAGE"; do
    [[ "$(docker image inspect "$service_image" --format '{{index .Config.Labels "org.opencontainers.image.revision"}}')" == "$target_sha" ]]
  done

  if test -s "$current_state"; then
    (load_state "$current_state")
  elif docker ps -q \
    --filter label=com.docker.compose.project=hirescope-ai \
    --filter label=com.docker.compose.service=api | grep -q .; then
      snapshot_legacy_rollback_state "$COMPOSE_FILE"
      set_image_environment
  else
    echo "No running application baseline exists; the first deployment cannot roll back applications automatically."
  fi

  run_migration compose

  local new_containers_started=false
  on_deploy_failure() {
    local exit_status=$?
    trap - ERR
    if [[ "$new_containers_started" == true ]]; then
      echo "New application containers failed; attempting app-only rollback." >&2
      rollback_apps || true
    fi
    exit "$exit_status"
  }
  trap on_deploy_failure ERR

  new_containers_started=true
  "${compose[@]}" up --no-deps -d --force-recreate api worker web
  wait_for_app_services compose
  verify_running_service compose api "$API_IMAGE" "$target_sha"
  verify_running_service compose worker "$WORKER_IMAGE" "$target_sha"
  verify_running_service compose web "$WEB_IMAGE" "$target_sha"

  local nonce
  nonce="${target_sha}-$(date +%s%N)"
  local headers_file body_file
  headers_file="$(mktemp)"
  body_file="$(mktemp)"
  trap 'rm -f "$headers_file" "$body_file"; trap - RETURN' RETURN

  curl -fsS --connect-timeout 5 --max-time "$health_command_timeout_seconds" \
    -H 'Cache-Control: no-cache' -D "$headers_file" -o "$body_file" \
    "http://127.0.0.1:3000/api/v1/version?deploy_sha=${target_sha}&nonce=${nonce}"
  grep -Eiq '^cache-control:.*no-store' "$headers_file"
  grep -Fq "\"commitSha\":\"${target_sha}\"" "$body_file"

  curl -fsS --connect-timeout 5 --max-time "$health_command_timeout_seconds" \
    -H 'Cache-Control: no-cache' -D "$headers_file" -o "$body_file" \
    "http://127.0.0.1:3000/_version?deploy_sha=${target_sha}&nonce=${nonce}"
  grep -Eiq '^cache-control:.*no-store' "$headers_file"
  grep -Eiq "^x-app-commit-sha: *${target_sha}" "$headers_file"
  grep -Eiq "^x-next-build-id: *${target_sha}" "$headers_file"
  grep -Fq "\"commitSha\":\"${target_sha}\"" "$body_file"
  grep -Fq "\"nextBuildId\":\"${target_sha}\"" "$body_file"

  local worker_id
  worker_id="$(run_health_command "worker log container lookup" "${compose[@]}" ps -q worker)"
  local worker_logs
  worker_logs="$(run_health_command "worker startup log lookup" docker logs "$worker_id" 2>&1)"
  grep -Fq "Worker starting commit_sha=${target_sha}" <<< "$worker_logs"

  trap - ERR
  record_success "$target_sha" \
    "$API_IMAGE" "$API_DIGEST" "$WORKER_IMAGE" "$WORKER_DIGEST" \
    "$WEB_IMAGE" "$WEB_DIGEST" "$MIGRATE_IMAGE" "$MIGRATE_DIGEST"
  echo "Internal image, OCI revision, runtime SHA, API, Web, and Worker checks passed for $target_sha."
}

record_success() {
  local target_sha="$1"
  API_IMAGE="$2"
  API_DIGEST="$3"
  WORKER_IMAGE="$4"
  WORKER_DIGEST="$5"
  WEB_IMAGE="$6"
  WEB_DIGEST="$7"
  MIGRATE_IMAGE="$8"
  MIGRATE_DIGEST="$9"
  COMPOSE_FILE="$state_dir/compose-${target_sha}.yml"

  require_sha "$target_sha"
  for digest in "$API_DIGEST" "$WORKER_DIGEST" "$WEB_DIGEST" "$MIGRATE_DIGEST"; do require_digest "$digest"; done
  test -s "$COMPOSE_FILE"
  if test -s "$current_state"; then cp "$current_state" "$previous_state"; fi
  umask 077
  {
    printf 'STATE_KIND=immutable\n'
    printf 'DEPLOY_SHA=%q\n' "$target_sha"
    printf 'API_IMAGE=%q\nAPI_DIGEST=%q\n' "$API_IMAGE" "$API_DIGEST"
    printf 'WORKER_IMAGE=%q\nWORKER_DIGEST=%q\n' "$WORKER_IMAGE" "$WORKER_DIGEST"
    printf 'WEB_IMAGE=%q\nWEB_DIGEST=%q\n' "$WEB_IMAGE" "$WEB_DIGEST"
    printf 'MIGRATE_IMAGE=%q\nMIGRATE_DIGEST=%q\n' "$MIGRATE_IMAGE" "$MIGRATE_DIGEST"
    printf 'COMPOSE_FILE=%q\n' "$COMPOSE_FILE"
  } > "${current_state}.tmp"
  mv "${current_state}.tmp" "$current_state"
  echo "Recorded successful production deployment $target_sha."
}

case "$action" in
  deploy)
    (( $# == 1 )) || { echo "Usage: $0 deploy <full-commit-sha>" >&2; exit 2; }
    install -d -m 700 "$state_dir"
    exec 9>"$deployment_lock"
    flock -n 9 || { echo "Another production deployment is already running." >&2; exit 1; }
    deploy "$@"
    ;;
  rollback)
    (( $# == 0 )) || { echo "Usage: $0 rollback" >&2; exit 2; }
    install -d -m 700 "$state_dir"
    exec 9>"$deployment_lock"
    flock -n 9 || { echo "Another production deployment is already running." >&2; exit 1; }
    rollback_apps
    ;;
  *)
    echo "Unknown action: $action" >&2
    exit 2
    ;;
esac
