import{ArrowRight,BookOpen,ChevronDown,FileText,LifeBuoy,Mail,MessageCircle,Search,ShieldCheck,UploadCloud}from"lucide-react";import Link from"next/link";import{Logo}from"../../components/Logo";import{HelpRevealManager}from"../../components/HelpRevealManager";import{SiteHeader}from"../../components/SiteHeader";
const categories=[[BookOpen,"新手入门","了解注册登录、角色选择和基础使用流程。"],[UploadCloud,"项目上传","查看 ZIP 上传、GitHub 导入和项目格式要求。"],[FileText,"报告与面试","了解 AI 审查、模拟面试和能力报告内容。"],[ShieldCheck,"账号与安全","了解项目隐私、授权分享和数据保护。"]]as const;
const questions=[["1. 支持哪些项目上传方式？","支持 ZIP 项目包上传，也支持 GitHub 仓库地址导入。"],["2. AI 审查需要多久？","取决于项目大小，MVP 阶段通常需要 1–3 分钟。"],["3. AI 会审查哪些内容？","系统会分析技术栈、目录结构、核心模块、代码质量与风险点。"],["4. 模拟面试可以重新进行吗？","可以。每次面试会基于当前项目内容生成新的递进问题。"],["5. 报告可以分享给面试官吗？","可以通过授权链接分享，并设置内容权限与有效期。"],["6. 面试官能直接看到我的项目吗？","只有在你明确授权后，指定面试官才能查看允许展示的内容。"]]as const;
export default function HelpPage(){return <><SiteHeader/><main className="help-center-page"><HelpRevealManager/>
<section className="help-hero help-reveal-section is-visible"><div className="help-container help-hero-grid"><div data-help-reveal-item><h1>帮助中心</h1><p>快速了解码途 AI 的使用方式、报告生成与数据安全。</p><label><Search/><input aria-label="搜索问题" placeholder="搜索问题，例如：如何上传项目？"/></label></div><div className="help-art" data-help-reveal-item><article><i/><i/><i/><i/></article><article><MessageCircle/><i/><i/></article><article><i/><i/><i/></article></div></div></section>
<section className="help-section help-reveal-section"><div className="help-container" data-help-reveal-item><h2>帮助分类</h2><div className="help-category-grid">{categories.map(([Icon,title,text])=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p><a href="#questions">查看问题 <ArrowRight/></a></article>)}</div></div></section>
<section id="questions" className="help-section help-reveal-section"><div className="help-container" data-help-reveal-item><h2>热门问题</h2><div className="help-questions">{questions.map(([question,answer],index)=><details key={question} open={index<2}><summary>{question}<ChevronDown/></summary><p>{answer}</p></details>)}</div></div></section>
<section className="help-section help-reveal-section"><div className="help-container" data-help-reveal-item><h2>联系支持</h2><p className="help-support-copy">没有找到答案？我们的支持团队可以帮助你解决项目上传、报告生成和账号使用问题。</p><div className="support-grid"><article><LifeBuoy/><b>在线客服</b><span>工作日 9:00 - 18:00</span></article><article><Mail/><b>发送邮件</b><a href="mailto:support@hirescope.ai">support@hirescope.ai</a></article><article><MessageCircle/><b>反馈建议</b><span>帮助我们改进码途 AI</span></article></div><div className="help-cta"><h2>开始你的第一次项目能力评估</h2><p>上传项目，获得 AI 审查与能力报告，提升面试通过率。</p><div><Link href="/login">立即体验</Link><Link href="/process">查看使用流程</Link></div></div></div></section>
<footer className="help-footer"><div><Logo/><p>让项目能力被看见，让优秀人才脱颖而出。</p></div><dl><div><dt>产品</dt><dd>产品能力</dd><dd>使用流程</dd><dd>报告示例</dd><dd>角色入口</dd></div><div><dt>资源</dt><dd>帮助中心</dd><dd>博客</dd><dd>更新日志</dd></div><div><dt>关于</dt><dd>关于我们</dd><dd>加入我们</dd><dd>联系我们</dd></div><div><dt>关注我们</dt><dd>微信公众号</dd><dd>小红书</dd><dd>Bilibili</dd></div></dl><small>© 2026 码途 AI · HireScope AI</small></footer>
</main></>}
