import { INestApplication } from '@nestjs/common'; import { Test } from '@nestjs/testing'; import { InterviewDifficulty, InterviewStatus, PrismaClient, ProjectStatus, TaskStatus, TaskType } from '@prisma/client'; import request from 'supertest'; import { afterAll, beforeAll, describe, expect, it } from 'vitest'; import { AppModule } from '../src/app.module'; import { configureApplication } from '../src/bootstrap'; import { TASK_QUEUE } from '../src/tasks/task-queue.service';
describe('Interviews API', () => {
  const prisma = new PrismaClient(); let app: INestApplication; let failedApp: INestApplication; let token: string; let otherToken: string; let userId: string; let otherUserId: string; let completedId: string; let generatingId: string; const auth = () => ({ Authorization: `Bearer ${token}` });
  beforeAll(async () => { const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).overrideProvider(TASK_QUEUE).useValue({ add: async () => undefined }).compile(); app = moduleRef.createNestApplication(); configureApplication(app); await app.init(); for (const email of ['interviews-e2e@example.com','interviews-other@example.com']) await request(app.getHttpServer()).post('/api/v1/auth/register').send({ email, password: 'StrongPassword123!' }); token = (await request(app.getHttpServer()).post('/api/v1/auth/login').send({ email: 'interviews-e2e@example.com', password: 'StrongPassword123!' })).body.accessToken; otherToken = (await request(app.getHttpServer()).post('/api/v1/auth/login').send({ email: 'interviews-other@example.com', password: 'StrongPassword123!' })).body.accessToken; userId = (await prisma.user.findUniqueOrThrow({ where: { email: 'interviews-e2e@example.com' } })).id; otherUserId = (await prisma.user.findUniqueOrThrow({ where: { email: 'interviews-other@example.com' } })).id; completedId = (await project(userId, ProjectStatus.COMPLETED, 'Completed')).id; });
  afterAll(async () => { await prisma.user.deleteMany({ where: { email: { startsWith: 'interviews-' } } }); await prisma.$disconnect(); if (failedApp) await failedApp.close(); await app.close(); });
  function project(owner: string, status: ProjectStatus, name: string) { return prisma.project.create({ data: { userId: owner, name, originalFileName: 'x.zip', fileSize: 4n, fileHash: 'b'.repeat(64), status } }); }
  it('validates authentication and DTO', async () => { expect((await request(app.getHttpServer()).post(`/api/v1/projects/${completedId}/interviews`).send({ questionCount: 8, difficulty: 'MEDIUM' })).status).toBe(401); for (const body of [{ questionCount: 4, difficulty: 'MEDIUM' }, { questionCount: 16, difficulty: 'MEDIUM' }, { questionCount: 8, difficulty: 'UNKNOWN' }]) expect((await request(app.getHttpServer()).post(`/api/v1/projects/${completedId}/interviews`).set(auth()).send(body)).status).toBe(422); });
  it('enforces ownership and project states', async () => { const foreign = await project(otherUserId, ProjectStatus.COMPLETED, 'Foreign'); expect((await request(app.getHttpServer()).post(`/api/v1/projects/${foreign.id}/interviews`).set(auth()).send({ questionCount: 8, difficulty: 'MEDIUM' })).status).toBe(404); for (const status of [ProjectStatus.DELETING, ProjectStatus.DELETED]) { const value = await project(userId, status, status); expect((await request(app.getHttpServer()).post(`/api/v1/projects/${value.id}/interviews`).set(auth()).send({ questionCount: 8, difficulty: 'MEDIUM' })).status).toBe(404); } const notReady = await project(userId, ProjectStatus.ANALYZING, 'Not ready'); const response = await request(app.getHttpServer()).post(`/api/v1/projects/${notReady.id}/interviews`).set(auth()).send({ questionCount: 8, difficulty: 'MEDIUM' }); expect(response.status).toBe(409); expect(response.body.error.code).toBe('PROJECT_NOT_READY'); });
  it('creates GENERATING interview and hides questions', async () => { const response = await request(app.getHttpServer()).post(`/api/v1/projects/${completedId}/interviews`).set(auth()).send({ questionCount: 8, difficulty: 'MEDIUM' }); expect(response.status, JSON.stringify(response.body)).toBe(202); expect(response.body).toMatchObject({ status: 'GENERATING', questionCount: 8, task: { type: 'INTERVIEW_QUESTION_GENERATION', status: 'QUEUED' } }); generatingId = response.body.id; const detail = await request(app.getHttpServer()).get(`/api/v1/interviews/${generatingId}`).set(auth()); expect(detail.status).toBe(200); expect(detail.body.questions).toBeUndefined(); });
  it('lists newest interviews with pagination', async () => { const older = await prisma.interview.create({ data: { userId, projectId: completedId, title: 'Older', status: InterviewStatus.FAILED, difficulty: InterviewDifficulty.EASY, questionCount: 5, createdAt: new Date(0) } }); const response = await request(app.getHttpServer()).get(`/api/v1/projects/${completedId}/interviews?page=1&pageSize=10`).set(auth()); expect(response.status).toBe(200); expect(response.body.pagination.total).toBe(2); expect(response.body.items[0].id).toBe(generatingId); expect(response.body.items[1].id).toBe(older.id); });
  it('returns READY questions in sequence without referencePoints', async () => { const ready = await prisma.interview.create({ data: { userId, projectId: completedId, title: 'Ready', status: InterviewStatus.READY, difficulty: InterviewDifficulty.HARD, questionCount: 5, questions: { create: [2,1].map((sequence) => ({ sequence, category: 'architecture', difficulty: InterviewDifficulty.HARD, question: `Q${sequence}`, referencePoints: ['secret'] })) } } }); const response = await request(app.getHttpServer()).get(`/api/v1/interviews/${ready.id}`).set(auth()); expect(response.status).toBe(200); expect(response.body.questions.map((value: any) => value.sequence)).toEqual([1,2]); expect(response.body.questions[0].referencePoints).toBeUndefined(); expect((await request(app.getHttpServer()).get(`/api/v1/interviews/${ready.id}`).set('Authorization', `Bearer ${otherToken}`)).status).toBe(404); });
  it('serializes concurrent creation as 202 and 409 without an orphan', async () => { const value = await project(userId, ProjectStatus.COMPLETED, 'Concurrent'); const responses = await Promise.all([1,2].map(() => request(app.getHttpServer()).post(`/api/v1/projects/${value.id}/interviews`).set(auth()).send({ questionCount: 8, difficulty: 'MEDIUM' }))); expect(responses.map((item) => item.status).sort()).toEqual([202,409]); expect(await prisma.interview.count({ where: { projectId: value.id } })).toBe(1); });
  it('keeps PENDING and GENERATING when queue publication fails', async () => { const value = await project(userId, ProjectStatus.COMPLETED, 'Queue failure'); const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).overrideProvider(TASK_QUEUE).useValue({ add: async () => { throw new Error('redis'); } }).compile(); failedApp = moduleRef.createNestApplication(); configureApplication(failedApp); await failedApp.init(); const response = await request(failedApp.getHttpServer()).post(`/api/v1/projects/${value.id}/interviews`).set(auth()).send({ questionCount: 8, difficulty: 'MEDIUM' }); expect(response.status).toBe(503); const interview = await prisma.interview.findFirstOrThrow({ where: { projectId: value.id } }); const task = await prisma.asyncTask.findFirstOrThrow({ where: { interviewId: interview.id, type: TaskType.INTERVIEW_QUESTION_GENERATION } }); expect(interview.status).toBe(InterviewStatus.GENERATING); expect(task).toMatchObject({ status: TaskStatus.PENDING, bullJobId: null, codeReviewId: null }); });

  it('runs the complete start-answer-submit workflow safely', async () => {
    const interview = await prisma.interview.create({ data: { userId, projectId: completedId, title: 'Answering flow', status: InterviewStatus.READY, difficulty: InterviewDifficulty.MEDIUM, questionCount: 5, questions: { create: Array.from({ length: 5 }, (_, index) => ({ sequence: index + 1, category: 'general', difficulty: InterviewDifficulty.MEDIUM, question: `Question ${index + 1}`, referencePoints: ['private point'] })) } }, include: { questions: { orderBy: { sequence: 'asc' } } } });
    const start = await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/start`).set(auth()); expect(start.status).toBe(201); expect(start.body.status).toBe('IN_PROGRESS'); expect(start.body.startedAt).toBeTruthy(); expect((await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/start`).set(auth())).body.status).toBe('IN_PROGRESS'); expect((await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/start`).set('Authorization', `Bearer ${otherToken}`)).status).toBe(404);
    const first = interview.questions[0]!; expect((await request(app.getHttpServer()).put(`/api/v1/interviews/${interview.id}/answers/${first.id}`).set(auth()).send({ content: '   ' })).body.error.code).toBe('ANSWER_CONTENT_EMPTY'); expect((await request(app.getHttpServer()).put(`/api/v1/interviews/${interview.id}/answers/${first.id}`).set(auth()).send({ content: 'a'.repeat(5001) })).body.error.code).toBe('ANSWER_CONTENT_TOO_LONG');
    const foreignInterview = await prisma.interview.create({ data: { userId, projectId: completedId, title: 'Foreign question holder', status: InterviewStatus.READY, difficulty: InterviewDifficulty.EASY, questionCount: 5, questions: { create: { sequence: 1, category: 'other', difficulty: InterviewDifficulty.EASY, question: 'Other', referencePoints: [] } } }, include: { questions: true } }); expect((await request(app.getHttpServer()).put(`/api/v1/interviews/${interview.id}/answers/${foreignInterview.questions[0]!.id}`).set(auth()).send({ content: 'wrong relation' })).status).toBe(404); expect((await request(app.getHttpServer()).put(`/api/v1/interviews/${interview.id}/answers/${first.id}`).set('Authorization', `Bearer ${otherToken}`).send({ content: 'foreign' })).status).toBe(404);
    await request(app.getHttpServer()).put(`/api/v1/interviews/${interview.id}/answers/${interview.questions[4]!.id}`).set(auth()).send({ content: 'Answer 5' }).expect(200); await request(app.getHttpServer()).put(`/api/v1/interviews/${interview.id}/answers/${first.id}`).set(auth()).send({ content: '  First version  ' }).expect(200); await request(app.getHttpServer()).put(`/api/v1/interviews/${interview.id}/answers/${first.id}`).set(auth()).send({ content: '  Final answer  ' }).expect(200);
    const incomplete = await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/submit`).set(auth()); expect(incomplete.status).toBe(409); expect(incomplete.body.error.code).toBe('INTERVIEW_NOT_COMPLETE');
    for (const question of interview.questions.slice(1, 4)) await request(app.getHttpServer()).put(`/api/v1/interviews/${interview.id}/answers/${question.id}`).set(auth()).send({ content: `Answer ${question.sequence}` }).expect(200);
    const beforeSubmit = await request(app.getHttpServer()).get(`/api/v1/interviews/${interview.id}`).set(auth()); expect(beforeSubmit.body).toMatchObject({ status: 'IN_PROGRESS', currentIndex: 5, answeredCount: 5, answerProgress: { answeredCount: 5, questionCount: 5, percentage: 100 } }); expect(beforeSubmit.body.questions[0].answer.content).toBe('Final answer'); expect(beforeSubmit.body.questions.every((question: any) => question.referencePoints === undefined)).toBe(true);
    const submitted = await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/submit`).set(auth()); expect(submitted.status).toBe(201); expect(submitted.body).toMatchObject({ status: 'SUBMITTED', currentIndex: 5, answeredCount: 5 }); expect(submitted.body.submittedAt).toBeTruthy(); expect(await prisma.asyncTask.count({ where: { interviewId: interview.id, type: TaskType.INTERVIEW_REPORT_GENERATION } })).toBe(0); expect((await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/submit`).set(auth())).body.status).toBe('SUBMITTED'); expect((await request(app.getHttpServer()).put(`/api/v1/interviews/${interview.id}/answers/${first.id}`).set(auth()).send({ content: 'late edit' })).status).toBe(409); expect((await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/start`).set(auth())).status).toBe(409);
  });

  it('creates, polls, and returns a safe interview report idempotently', async () => {
    const interview = await prisma.interview.create({ data: { userId, projectId: completedId, title: 'Report flow', status: InterviewStatus.SUBMITTED, difficulty: InterviewDifficulty.MEDIUM, questionCount: 5, submittedAt: new Date(), questions: { create: Array.from({ length: 5 }, (_, index) => ({ sequence: index + 1, category: 'architecture', difficulty: InterviewDifficulty.MEDIUM, question: `How ${index + 1}?`, referencePoints: ['private-reference'] })) } }, include: { questions: true } });
    await prisma.interviewAnswer.createMany({ data: interview.questions.map((question) => ({ userId, interviewId: interview.id, questionId: question.id, content: 'Detailed answer' })) });
    const missing = await request(app.getHttpServer()).get(`/api/v1/interviews/${interview.id}/report`).set(auth()); expect(missing.status).toBe(404); expect(missing.body.error.code).toBe('INTERVIEW_REPORT_NOT_FOUND');
    const created = await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/report`).set(auth()); expect(created.status, JSON.stringify(created.body)).toBe(202); expect(created.body).toMatchObject({ interview: { id: interview.id, status: 'REPORT_GENERATING' }, task: { type: 'INTERVIEW_REPORT_GENERATION', status: 'QUEUED' } });
    const task = await prisma.asyncTask.findFirstOrThrow({ where: { interviewId: interview.id, type: TaskType.INTERVIEW_REPORT_GENERATION } }); expect(task).toMatchObject({ userId, projectId: completedId, codeReviewId: null, status: TaskStatus.QUEUED, bullJobId: task.id });
    const duplicate = await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/report`).set(auth()); expect(duplicate.status).toBe(202); expect(duplicate.body.task.id).toBe(task.id);
    expect((await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/report`).set('Authorization', `Bearer ${otherToken}`)).status).toBe(404);
    expect((await request(app.getHttpServer()).get(`/api/v1/interviews/${interview.id}/report`).set(auth())).body).toEqual({ status: 'REPORT_GENERATING', report: null });
    await prisma.$transaction([prisma.interviewReport.create({ data: { interviewId: interview.id, userId, overallScore: 82, summary: 'Stable report', dimensions: { projectUnderstanding: 82, technicalAccuracy: 82, communication: 82, problemSolving: 82 }, questionReviews: [{ questionId: 'hidden', sequence: 1, score: 82, comment: 'ok', matchedReferencePoints: 1, totalReferencePoints: 1 }], strengths: ['strength'], improvements: ['improvement'], result: { referencePoints: ['must-not-leak'] }, model: 'deterministic-interview-report-v1' } }), prisma.interview.update({ where: { id: interview.id }, data: { status: InterviewStatus.COMPLETED, completedAt: new Date() } }), prisma.asyncTask.update({ where: { id: task.id }, data: { status: TaskStatus.SUCCEEDED, completedAt: new Date() } })]);
    const completed = await request(app.getHttpServer()).get(`/api/v1/interviews/${interview.id}/report`).set(auth()); expect(completed.status).toBe(200); expect(completed.body).toMatchObject({ status: 'COMPLETED', report: { overallScore: 82, summary: 'Stable report', model: 'deterministic-interview-report-v1' } }); expect(completed.body.report.result).toBeUndefined(); expect(JSON.stringify(completed.body)).not.toContain('referencePoints');
    const completedRetry = await request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/report`).set(auth()); expect(completedRetry.status).toBe(202); expect(completedRetry.body.report.overallScore).toBe(82); expect(await prisma.asyncTask.count({ where: { interviewId: interview.id, type: TaskType.INTERVIEW_REPORT_GENERATION } })).toBe(1);
  });

  it('serializes concurrent report creation to one active task', async () => {
    const interview = await prisma.interview.create({ data: { userId, projectId: completedId, title: 'Concurrent report', status: InterviewStatus.SUBMITTED, difficulty: InterviewDifficulty.EASY, questionCount: 5, submittedAt: new Date() } });
    const responses = await Promise.all([1, 2].map(() => request(app.getHttpServer()).post(`/api/v1/interviews/${interview.id}/report`).set(auth())));
    expect(responses.map((response) => response.status).sort()).toEqual(expect.arrayContaining([202]));
    expect(responses.every((response) => response.status === 202 || response.status === 409), JSON.stringify(responses.map((response) => ({ status: response.status, body: response.body })))).toBe(true);
    expect(new Set(responses.filter((response) => response.status === 202).map((response) => response.body.task.id)).size).toBe(1);
    expect(await prisma.asyncTask.count({ where: { interviewId: interview.id, type: TaskType.INTERVIEW_REPORT_GENERATION, status: { in: [TaskStatus.PENDING, TaskStatus.QUEUED, TaskStatus.PROCESSING] } } })).toBe(1);
  });

  it('keeps a report task PENDING and interview REPORT_GENERATING when publication fails', async () => {
    const interview = await prisma.interview.create({ data: { userId, projectId: completedId, title: 'Report queue failure', status: InterviewStatus.SUBMITTED, difficulty: InterviewDifficulty.EASY, questionCount: 5, submittedAt: new Date() } });
    const response = await request(failedApp.getHttpServer()).post(`/api/v1/interviews/${interview.id}/report`).set(auth()); expect(response.status).toBe(503); expect(response.body.error.code).toBe('QUEUE_UNAVAILABLE');
    expect(await prisma.interview.findUnique({ where: { id: interview.id } })).toMatchObject({ status: InterviewStatus.REPORT_GENERATING });
    expect(await prisma.asyncTask.findFirst({ where: { interviewId: interview.id } })).toMatchObject({ type: TaskType.INTERVIEW_REPORT_GENERATION, status: TaskStatus.PENDING, bullJobId: null });
  });
});
