import { InterviewDifficulty, InterviewStatus, ProjectStatus, TaskStatus, TaskType } from '@prisma/client'; import { describe, expect, it, vi } from 'vitest'; import { InterviewQuestionGenerationError } from '../interview/ai-interview-question.service'; import { InterviewQuestionProcessor } from './interview-question.processor';
function task(projectStatus: ProjectStatus = ProjectStatus.COMPLETED, interviewStatus: InterviewStatus = InterviewStatus.GENERATING, taskStatus: TaskStatus = TaskStatus.QUEUED): any { return { id: 'task', userId: 'user', type: TaskType.INTERVIEW_QUESTION_GENERATION, status: taskStatus, projectId: 'project', interviewId: 'interview', interview: { id: 'interview', status: interviewStatus, questionCount: 5, difficulty: InterviewDifficulty.MEDIUM }, project: { id: 'project', status: projectStatus, analysis: { summary: 'summary', techStack: [], coreModules: [], statistics: {} }, codeReviews: [] } }; }
const valid = { questions: Array.from({ length: 5 }, (_, index) => ({ sequence: index + 1, category: 'general', difficulty: 'MEDIUM', question: `Question ${index + 1}`, referencePoints: ['point'] })) };
function setup(value: any = task(), generated: any = valid) { const tx = { $queryRaw: vi.fn().mockResolvedValue([{ interviewStatus: value.interview.status, projectStatus: value.project.status }]), asyncTask: { update: vi.fn(), updateMany: vi.fn().mockResolvedValue({ count: 1 }) }, interview: { update: vi.fn() }, interviewQuestion: { createMany: vi.fn() } }; const prisma = { asyncTask: { findUnique: vi.fn().mockResolvedValue(value) }, $transaction: vi.fn((callback) => callback(tx)) }; const generator = { generate: vi.fn().mockReturnValue(generated) }; return { tx, prisma, generator, processor: new InterviewQuestionProcessor(prisma as never, generator as never) }; }
describe('InterviewQuestionProcessor', () => {
  it('writes all questions and terminal states atomically', async () => { const { processor, tx } = setup(); await processor.process('task'); expect(tx.interviewQuestion.createMany).toHaveBeenCalledWith({ data: expect.arrayContaining([expect.objectContaining({ interviewId: 'interview', sequence: 1 })]) }); expect(tx.interview.update).toHaveBeenLastCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: InterviewStatus.READY }) })); expect(tx.asyncTask.update).toHaveBeenLastCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: TaskStatus.SUCCEEDED, progress: 100 }) })); });
  it('fails invalid output without writing partial questions', async () => { const { processor, tx } = setup(task(), { questions: [{ sequence: 1 }] }); await processor.process('task'); expect(tx.interviewQuestion.createMany).not.toHaveBeenCalled(); expect(tx.interview.update).toHaveBeenLastCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: InterviewStatus.FAILED, failureCode: 'INTERVIEW_QUESTIONS_RESULT_INVALID' }) })); });
  it('cancels deleting projects without writing questions', async () => { const { processor, tx, generator } = setup(task(ProjectStatus.DELETING)); await processor.process('task'); expect(generator.generate).not.toHaveBeenCalled(); expect(tx.interviewQuestion.createMany).not.toHaveBeenCalled(); expect(tx.asyncTask.update).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: TaskStatus.CANCELLED, failureCode: 'RESOURCE_DELETING' }) })); });
  it('fails interview when project is not completed', async () => { const { processor, tx } = setup(task(ProjectStatus.FAILED)); await processor.process('task'); expect(tx.interview.update).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: InterviewStatus.FAILED, failureCode: 'PROJECT_NOT_READY' }) })); });
  it('returns idempotently when interview is READY', async () => { const { processor, generator, tx } = setup(task(ProjectStatus.COMPLETED, InterviewStatus.READY, TaskStatus.SUCCEEDED)); await processor.process('task'); expect(generator.generate).not.toHaveBeenCalled(); expect(tx.interviewQuestion.createMany).not.toHaveBeenCalled(); });
  it('maps provider failures to terminal task state without partial writes', async () => { const { processor, generator, tx } = setup(); generator.generate.mockRejectedValue(new InterviewQuestionGenerationError('AI_RATE_LIMITED')); await processor.process('task'); expect(tx.interviewQuestion.createMany).not.toHaveBeenCalled(); expect(tx.asyncTask.update).toHaveBeenLastCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: TaskStatus.FAILED, failureCode: 'AI_RATE_LIMITED' }) })); });
  it('does not write questions twice when a completed job is delivered again', async () => { const { processor, prisma, tx } = setup(); const ready = task(ProjectStatus.COMPLETED, InterviewStatus.READY, TaskStatus.SUCCEEDED); prisma.asyncTask.findUnique.mockResolvedValueOnce(task()).mockResolvedValueOnce(ready); await processor.process('task'); await processor.process('task'); expect(tx.interviewQuestion.createMany).toHaveBeenCalledTimes(1); });
});
